### ISSUE TITLE
There is no payment

### ISSUE THREAD

**Issue by ronyfsx2013** [HarryCatraz/FiveM-vRP-Dunko-Version-Catraz-Edit#1]
hello the pay of the bus work is not falling

**Comment by HarryCatraz** [comment]
Hi Ronyfsx2013,

Could you explain the issue in more detail.

From your post am i correct in thinking the Bus Job does not pay the player.

If so ill add it to the list of fixes and will take a look and hopefully fix tonight.

Kind Regards,
Catraz

**Comment by HarryCatraz** [comment]
No Reply after 6 days.

Open a new issue if persists.
Issue Closed and moved
